image: python:3.9

options:
  # Set maximum execution time for each step
  max-time: 5

pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - apt-get update
          - apt-get -y install unixodbc-dev
          - pip install tox
          - tox -e py39
