parameters:
- name: pythonVersion
  type: string
- name: MsiTargetType
  type: string

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '${{parameters.pythonVersion}}'
    displayName: 'Use Python ${{parameters.pythonVersion}}'     

  - bash: |
      set -ex
      python -m venv venv_msi_build
      source venv_msi_build/scripts/activate
      python -m pip install --upgrade pip
      pip install artifacts-keyring --no-input
      set ARTIFACTS_KEYRING_NONINTERACTIVE_MODE=true
      pip config set global.index-url $(ArtifactsIndexURL) 
      pip install .[msibuild]
      export PALJE_MSI_TARGET_TYPE=${{parameters.MsiTargetType}}
      python ./msi_build.py bdist_msi
      deactivate
      pip install wheel twine
      python -m pip wheel . -w dist --no-deps
    displayName: "Build MSI-installer"

  - task: DotNetCoreCLI@2
    inputs:
      command: 'custom'
      custom: 'tool'
      arguments: 'install --global azuresigntool'
    displayName: Install AzureSignTool

  - bash: |
      AzureSignTool sign -kvu "$(kvURI)" -kvi $(ApplicationId) -kvt $(TenantId) -kvs $(ClientSecret) -kvc $(certName) -tr "http://ts.ssl.com" -td sha256 D:/a/1/s/dist/*.msi
    displayName: Sign all msi-files in artefacts-directory

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: 'dist'
    displayName: Publish msi-file as a pipeline artifact