parameters:
- name: pythonVersion
  type: string

steps:
  - task: usePythonVersion@0
    inputs:
      versionSpec: '${{parameters.pythonVersion}}'
    displayName: 'Use Python ${{parameters.pythonVersion}}'

  - bash: |
      set -ex
      python -m venv .testvenv
      source .testvenv/bin/activate
      python -m pip install --upgrade pip
      pip install artifacts-keyring --no-input
      set ARTIFACTS_KEYRING_NONINTERACTIVE_MODE=true
      pip config set global.index-url $(ArtifactsIndexURL) 
      pip install -e .
      pip install pytest pytest-aiohttp pytest-cov pytest-azurepipelines ahjo sqlalchemy
    displayName: 'Set up testenv' 

  - bash: |
      set -ex
      source .testvenv/bin/activate
      pytest --cov=src --cov-report=html
    displayName: 'Run unit tests and code coverage'

  - task: PublishCodeCoverageResults@2
    inputs:
      summaryFileLocation: '$(Build.SourcesDirectory)/coverage.xml'
    displayName: 'Publish code coverage results to ADO GUI'